import type { AddonManifest } from './types'

function localId(id: string): string {
  return id.includes(':') ? id.split(':')[1] : id
}

function tomlString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, ' ')
}

export function neoforgeModId(manifest: AddonManifest): string {
  return localId(manifest.id).replace(/[^a-z0-9_]/gi, '_').toLowerCase()
}

export function buildNeoForgeModsToml(manifest: AddonManifest): string {
  const modId = neoforgeModId(manifest)
  const issueTracker = manifest.support?.issues ? `issueTrackerURL="${tomlString(manifest.support.issues)}"\n` : ''
  return [
    '# Generated by ECHO Studio',
    'modLoader="javafml"',
    'loaderVersion="[1,)"',
    'license="All Rights Reserved"',
    issueTracker.trimEnd(),
    '[[mods]]',
    `modId="${modId}"`,
    `version="${tomlString(manifest.version)}"`,
    `displayName="${tomlString(manifest.name)}"`,
    `description="${tomlString(manifest.description)}"`,
    '',
    `[[dependencies.${modId}]]`,
    'modId="neoforge"',
    'type="required"',
    'versionRange="[21,)"',
    'ordering="NONE"',
    'side="BOTH"',
    '',
    `[[dependencies.${modId}]]`,
    'modId="minecraft"',
    'type="required"',
    'versionRange="[1.21.1,1.22)"',
    'ordering="NONE"',
    'side="BOTH"',
    ''
  ].filter((line) => line.length > 0).join('\n')
}
